build:
  image: nikitati/rails
  environment:
    - RAILS_ENV=test
  commands:
    - 'n=0
    while [ $n -ge 60 ]
    do
      mysqladmin ping -h"127.0.0.1" --silent && break
      sleep 1
      n=$[$n+1]
    done'
    - cp config/database.drone.yml config/database.yml
    - bundle install
    - bundle exec rake db:create db:schema:load
    - bundle exec rspec spec --format documentation

compose:
  mysql:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATABASE=test_drone_test
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=test_drone
