compose:
  mysql:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes



build:
  image: nikitati/rails
  environment:
    - RAILS_ENV=test
  commands:
    - mysql -P 3306 -h 127.0.0.1 --protocol=tcp -u root -e 'create database if not exists drone;'
    - cp config/database.drone.yml config/database.yml
    - bundle install
    - bundle exec rake db:create db:schema:load
    - bundle exec rspec spec --format documentation
