build:
  image: nikitati/rails
  environment:
    - RAILS_ENV=test
  commands:
    - sleep 10 && mysql -h127.0.0.1 -u root -e 'create database if not exists drone;'

compose:
  mysql:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
