build:
  image: nikitati/rails
  environment:
    - RAILS_ENV=test
  commands:
    - sleep 100
    - mysql -h127.0.0.1 -u root -e 'create database if not exists drone;'

compose:
  database:
    image: mysql:5.7
