build:
  image: nikitati/rails
  environment:
    - RAILS_ENV=test
    - TEST_CLUSTER_COMMAND=/usr/share/elasticsearch/bin/elasticsearch
  commands:
    - cp config/database.drone.yml config/database.yml
    - cp config/settings.example.yml config/settings.yml
    - mkdir -p /tmp/bundle
    # - bundle config build.nokogiri --use-system-libraries
    # - gem install nokogiri -v '1.6.6.2'
    - bundle install --path /tmp/bundle
    # - chmod +x ./ci/wailmysql.sh && ./ci/wailmysql.sh
    # - bundle exec rake db:create db:schema:load
    # - bundle exec rspec spec --format documentation


compose:
  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  elastic:
      image: library/elasticsearch
  redis:
      image: redis

cache:
  mount:
    - /tmp/bundle
    # - .git
