build:
  image: nikitati/rails
  environment:
    - RAILS_ENV=test
  script:
    - cp config/database.drone.yml config/database.yml
    - bundle install
    - bundle exec rake tmp:create
    - bundle exec rake db:create db:schema:load
    - bundle exec rspec spec --format documentation

compose:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=test_drone_test
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=test_drone
