build:
  image: nikitati/rails
  environment:
    - RAILS_ENV=test
  commands:
    # - sleep 1 && mysql -h127.0.0.1 -u root -e 'create database if not exists drone;'
    - cp config/database.drone.yml config/database.yml
    - bundle install
    - sleep 10 && bundle exec rake db:create db:schema:load
    - sleep 10 && bundle exec rspec spec --format documentation

compose:
  mysql:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATABASE=test_drone_test
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=test_drone
