build:
  image: rails:4.2
  environment:
    - RAILS_ENV=test
  script:
    - cp config/database.drone.yml config/database.yml
    - mkdir -p /tmp/bundle
    - bundle install --path /tmp/bundle
    - bundle exec rake tmp:create
    - bundle exec rake db:create
    - bundle exec rake db:schema:load
    - bundle exec rspec spec --format documentation

compose:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=test_drone_test
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=test_drone
cache:
  mount:
    - /tmp/bundle
