build:
  image: nikitati/rails
  environment:
    - RAILS_ENV=test
  commands:
    - >
      #!/bin/bash\n
      n=0\n
      until [ $n -ge 60 ]; do\n
        mysqladmin ping -h"127.0.0.1" --silent && break\n
        sleep 1\n
        n=$[$n+1]\n
      done\n
    - mysqladmin ping -h"127.0.0.1"
    - cp config/database.drone.yml config/database.yml
    - bundle install
    - bundle exec rake db:create db:schema:load
    - bundle exec rspec spec --format documentation

compose:
  mysql:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATABASE=test_drone_test
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=test_drone
