build:
  image: eunix/drone-docker-inpos-core:2.2.1
  environment:
    - RAILS_ENV=test
    - TEST_CLUSTER_COMMAND=/usr/share/elasticsearch/bin/elasticsearch
  commands:
    - chmod +x ./ci/wailmysql.sh && ./ci/wailmysql.sh
    - cp config/database.drone.yml config/database.yml
    - cp config/settings.example.yml config/settings.yml
    - mkdir -p /tmp/bundle
    - sudo chown ubuntu:ubuntu /tmp/bundle
    - bundle install --quiet --path /tmp/bundle
    - bundle exec rake db:create db:schema:load
    - bundle exec rspec spec --format documentation

compose:
  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  elastic:
      image: library/elasticsearch
  redis:
      image: redis

cache:
  mount:
    - /tmp/bundle
    - .git
