debug: true
build:
  image: nikitati/rails
  environment:
    - RAILS_ENV=test
  commands:
    - mysql -P 3306 -h 127.0.0.1 -u root -e 'create database if not exists drone;'
    - cp config/database.drone.yml config/database.yml
    - bundle install
    - bundle exec rake db:create db:schema:load
    - bundle exec rspec spec --format documentation

compose:
  mysql:
    image: mysql
